# Generated by Django 4.1.5 on 2024-04-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket', to='store.company')),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='goods_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_company_name', models.CharField(max_length=121)),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds', to='store.company_goods')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfsf', to='store.company')),
            ],
        ),
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=120)),
                ('taluka', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('mobile_number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.company')),
            ],
        ),
    ]
