# Generated by Django 4.1.5 on 2023-04-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_goods',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='goods_company',
            unique_together={('company_goods', 'goods_company_name')},
        ),
    ]
