# Generated by Django 4.1.5 on 2023-04-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_goods_company_goods_company_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goods_company',
            unique_together={('company_name', 'company_goods', 'goods_company_name')},
        ),
    ]
