# Generated by Django 4.1.5 on 2024-04-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supply_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LR_number', models.CharField(blank=True, max_length=50, null=True)),
                ('freight', models.CharField(blank=True, max_length=50, null=True)),
                ('bags', models.BigIntegerField()),
                ('DC_number', models.CharField(max_length=50)),
                ('DC_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fgrrt', to='store.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wegvge', to='store.goods_company')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scxsesdf', to='store.transport')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bag', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='store.goods_company')),
            ],
        ),
        migrations.CreateModel(
            name='outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LR_number', models.CharField(blank=True, max_length=50, null=True)),
                ('freight', models.CharField(blank=True, max_length=50, null=True)),
                ('bags', models.BigIntegerField()),
                ('DC_number', models.BigIntegerField()),
                ('DC_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='df', to='store.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fgv', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvg', to='store.goods_company')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ddssszc', to='store.transport')),
            ],
        ),
        migrations.CreateModel(
            name='inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LR_number', models.CharField(blank=True, max_length=50, null=True)),
                ('freight', models.CharField(blank=True, max_length=50, null=True)),
                ('bags', models.BigIntegerField()),
                ('DC_number', models.BigIntegerField()),
                ('DC_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv', to='store.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwe', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfgv', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xvc', to='store.goods_company')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdsxc', to='store.transport')),
            ],
        ),
    ]
