# Generated by Django 4.1.5 on 2024-04-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_entries', to='store.agent'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_entries', to='store.company'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='company_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_entries', to='store.company_goods'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='goods_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_entries', to='store.goods_company'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_entries', to='store.transport'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_entries', to='store.agent'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_entries', to='store.company'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='company_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_entries', to='store.company_goods'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='goods_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_entries', to='store.goods_company'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_entries', to='store.transport'),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_return_entries', to='store.agent'),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_return_entries', to='store.company'),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='company_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_return_entries', to='store.company_goods'),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='goods_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_return_entries', to='store.goods_company'),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_return_entries', to='store.transport'),
        ),
    ]
