# Generated by Django 3.2.15 on 2022-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_inward_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='freight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
