# Generated by Django 3.2.15 on 2022-12-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_alter_inward_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='DC_date',
            field=models.DateField(),
        ),
    ]
