# Generated by Django 3.2.15 on 2022-12-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_alter_supply_return_dc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_return',
            name='DC_number',
            field=models.CharField(max_length=50),
        ),
    ]
