# Generated by Django 4.1.5 on 2023-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_alter_inward_dc_date_alter_outward_dc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_return',
            name='DC_date',
            field=models.DateField(),
        ),
    ]
