# Generated by Django 4.1.5 on 2023-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_alter_supply_return_dc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='DC_date',
            field=models.DateTimeField(),
        ),
    ]
